### ISSUE TITLE
Make sauce

### ISSUE THREAD

**Issue by eliewa** [Warjumper/Kanban-pizza#1]
# Make Sauce

- Canned fire roasted tomatoes: Try to find this type of canned tomato if at all possible! Roasting tomatoes over an open flame brings a mellow, 
 sweet flavor right out of the can. Several brands carry this special type of tomato that’s become widely available. If you can’t find them, use the highest quality crushed tomatoes you can find.
- Small garlic clove: Garlic cloves widely vary in size. This recipe calls for a small clove — if you don’t have one, use half a medium or a quarter of a large clove (see the video below if you need a hint on sizes). This is important so the sauce doesn’t end up too garlicky.
- Dried oregano: Make sure to use dried oregano that’s fairly new so that the flavor is strong enough. If it’s been in your cabinet over 1 year, it’s time for a refresh!
- Olive oil: Use extra virgin olive oil. Always.
- Salt. No recipe is complete without salt (we always use kosher salt: here’s why).

**Comment by EbrahimLadhi** [comment]
Canned fire roasted tomatoes: Try to find this type of canned tomato if at all possible! Roasting tomatoes over an open flame brings a mellow, sweet flavor right out of the can. Several brands carry this special type of tomato that’s become widely available. If you can’t find them, use the highest quality crushed tomatoes you can find.
Small garlic clove: Garlic cloves widely vary in size. This recipe calls for a small clove — if you don’t have one, use half a medium or a quarter of a large clove (see the video below if you need a hint on sizes). This is important so the sauce doesn’t end up too garlicky.
Dried oregano: Make sure to use dried oregano that’s fairly new so that the flavor is strong enough. If it’s been in your cabinet over 1 year, it’s time for a refresh!
Olive oil: Use extra virgin olive oil. Always.
Salt. No recipe is complete without salt (we always use kosher salt: here’s why).

**Comment by darbecker12** [comment]
I'm still waiting on why we always use kosher salt but the canned fire roasted tomatoes sound like a great touch

**Comment by EbrahimLadhi** [comment]
Kosher Salt is popular among the youth plus some sect of religion. Roasted tomatoes goes hand in hand with perfect taste.

**Comment by Warjumper** [comment]
@darbecker12 Good catch, here is some insight as to why:

Kosher salt has wider, coarser grains vs table salt. The wider grains salt food in a gentler way than table salt. Using kosher salt enhances the flavor of foods instead of making them taste salty. Kosher salt has no iodine, which can lend a bitter taste to foods salted with table salt.
